/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnimalIdRouteImport } from './routes/animal.$id'
import { Route as AuthenticatedMeusAnunciosRouteImport } from './routes/_authenticated/meus-anuncios'
import { Route as AuthenticatedAnunciarRouteImport } from './routes/_authenticated/anunciar'
import { Route as AuthenticatedEditarIdRouteImport } from './routes/_authenticated/editar.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalIdRoute = AnimalIdRouteImport.update({
  id: '/animal/$id',
  path: '/animal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeusAnunciosRoute =
  AuthenticatedMeusAnunciosRouteImport.update({
    id: '/meus-anuncios',
    path: '/meus-anuncios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnunciarRoute = AuthenticatedAnunciarRouteImport.update({
  id: '/anunciar',
  path: '/anunciar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEditarIdRoute = AuthenticatedEditarIdRouteImport.update({
  id: '/editar/$id',
  path: '/editar/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/anunciar': typeof AuthenticatedAnunciarRoute
  '/meus-anuncios': typeof AuthenticatedMeusAnunciosRoute
  '/animal/$id': typeof AnimalIdRoute
  '/editar/$id': typeof AuthenticatedEditarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/anunciar': typeof AuthenticatedAnunciarRoute
  '/meus-anuncios': typeof AuthenticatedMeusAnunciosRoute
  '/animal/$id': typeof AnimalIdRoute
  '/editar/$id': typeof AuthenticatedEditarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/anunciar': typeof AuthenticatedAnunciarRoute
  '/_authenticated/meus-anuncios': typeof AuthenticatedMeusAnunciosRoute
  '/animal/$id': typeof AnimalIdRoute
  '/_authenticated/editar/$id': typeof AuthenticatedEditarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/anunciar'
    | '/meus-anuncios'
    | '/animal/$id'
    | '/editar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/anunciar'
    | '/meus-anuncios'
    | '/animal/$id'
    | '/editar/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/anunciar'
    | '/_authenticated/meus-anuncios'
    | '/animal/$id'
    | '/_authenticated/editar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AnimalIdRoute: typeof AnimalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animal/$id': {
      id: '/animal/$id'
      path: '/animal/$id'
      fullPath: '/animal/$id'
      preLoaderRoute: typeof AnimalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/meus-anuncios': {
      id: '/_authenticated/meus-anuncios'
      path: '/meus-anuncios'
      fullPath: '/meus-anuncios'
      preLoaderRoute: typeof AuthenticatedMeusAnunciosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anunciar': {
      id: '/_authenticated/anunciar'
      path: '/anunciar'
      fullPath: '/anunciar'
      preLoaderRoute: typeof AuthenticatedAnunciarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/editar/$id': {
      id: '/_authenticated/editar/$id'
      path: '/editar/$id'
      fullPath: '/editar/$id'
      preLoaderRoute: typeof AuthenticatedEditarIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnunciarRoute: typeof AuthenticatedAnunciarRoute
  AuthenticatedMeusAnunciosRoute: typeof AuthenticatedMeusAnunciosRoute
  AuthenticatedEditarIdRoute: typeof AuthenticatedEditarIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnunciarRoute: AuthenticatedAnunciarRoute,
  AuthenticatedMeusAnunciosRoute: AuthenticatedMeusAnunciosRoute,
  AuthenticatedEditarIdRoute: AuthenticatedEditarIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AnimalIdRoute: AnimalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
